import ThumbUpAltIcon from '@material-ui/icons/ThumbUpAlt';
const CourseData=[
    {
        title: "Arabic Language & Quranic Grammar 1st Semester ",
        cOutLine: " Learning Outcomes:",
        pOne: "Preliminary reading, writing, listening & speaking skills development",
        pTwo: "Approximately 300 vocabulary",
        pThree: "Preliminary sentence construction without harakat",
        pFour: "Habituate with grammar avoiding grammatical explanations",
        pFive: "",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Arabic Language & Quranic Grammar 2nd Semester ",
        cOutLine: "Learning Outcomes:",
        pOne: " Elementary reading, writing, listening & speaking skills development ",
        pTwo: "Approximately 250 vocabulary",
        pThree: "Constructing long sentences with a variety of forms without harakat ",
        pFour: "Understand selective texts of regular recitation from Quran & Sunnah",
        pFive: "Habituate with grammar avoiding grammatical explanations",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Arabic Language & Quranic Grammar 3rd Semester ",
        cOutLine: "Learning Outcomes:",
        pOne: " Secondary reading, writing, listening & speaking skills development ",
        pTwo: "Approximately 300 vocabulary",
        pThree: "Preliminary sentence construction without harakat ",
        pFour: "Integration of communicative Arabic grammar and fundamental Arabic grammar based on Nahu Meer (Iqna’ud Dameer)",
        pFive: "Understand approximately 80% of the scripts of Quran and Sunnah",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Arabic Language & Quranic Grammar Semester 4 – 6",
        cOutLine: "Learning Outcomes:",
        pOne: " Advanced reading, writing, listening & speaking skills development ",
        pTwo: "Approximately 900 vocabulary",
        pThree: "Constructing long complex sentences with a variety of forms without harakat",
        pFour: "Special reading skill i.e. reading the scripts of Hadith without harakat",
        pFive: "Obtaining grasp of the meaning by either reading or listening Quran",
        pSix: "Understand Arabic lectures (standard Arabic)",
        pSeven: "Integration of communicative Arabic grammar and fundamental Arabic grammar based on Matan al Ajrumiyyah ",
        pEight: "Understand 80-90% of the scripts of Quran and Sunnah",
        pNine: "",
        pTen: "",
    },
    {
        title: "Quran Reading & Reciting program 3 semesters ",
        cOutLine: "Learning Outcomes:",
        pOne: " Quran Reading program 3 semesters",
        pTwo: "1st Semester: Knowledge of Quranic alphabets and Makhraj (pronunciation), preliminary tajweed",
        pThree: "2nd Semester: Tilawatul Quran (Chapters 30, 29) and primary tajweed and ending criteria of an Ayat",
        pFour: "3rd Semester: Tilawatul Quran – Sura Baqara and Al-e-Imran with moderate tajweed",
        pFive: "",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Hifzul Quran Program ",
        cOutLine: "Learning Outcomes:",
        pOne: "1st Level: Chapters 30 & 29, Sura Baqara (Ayatul Kursi & last three verses), Sura Al-e-Imran (verses 189-194), Sura Kahf (first ten verses), Sura Loqman (verses 33,34), Sura Hashr (last 3 verses) ",
        pTwo: "2nd Level: Chapters 30 & 29, Sura Baqara (whole), Sura Al-e-Imran (whole)",
        pThree: "3rd Level: Gradual memorization of whole Quran ",
        pFour: "",
        pFive: "",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Fundamental Quranic Grammar 1st Semester ",
        cOutLine: "Learning Outcomes:",
        pOne: "Completely based on Quranic structure",
        pTwo: "100 – 150 Recurring Quranic words",
        pThree: "Completion of 10 – 15% Quranic Grammar",
        pFour: "Obtaining preliminary level of Fundamental Quranic",
        pFive: "",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Fundamental Quranic Grammar 1st Semester ",
        cOutLine: "Learning Outcomes:",
        pOne: "Completely based on Quranic structure",
        pTwo: "100 – 150 Recurring Quranic words",
        pThree: "Completion of 10 – 15% Quranic Grammar",
        pFour: "Obtaining preliminary level of Fundamental Quranic",
        pFive: "",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Fundamental Quranic Grammar 1st Semester ",
        cOutLine: "Learning Outcomes:",
        pOne: "Completely based on Quranic structure",
        pTwo: "100 – 150 Recurring Quranic words",
        pThree: "Completion of 10 – 15% Quranic Grammar",
        pFour: "Obtaining preliminary level of Fundamental Quranic",
        pFive: "",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Fundamental Quranic Grammar 2nd semester",
        cOutLine: "Learning Outcomes:",
        pOne: "Completely based on Quranic structure",
        pTwo: "100 – 150 new Recurring Quranic words",
        pThree: "Completion of 30 – 35% Quranic Grammar",
        pFour: "Obtaining primary level of Fundamental Quranic Grammar",
        pFive: "",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Fundamental Quraic Grammer 3rd semester",
        cOutLine: "Learning Outcomes:",
        pOne: "Completely based on Quraic structure",
        pTwo: "100 – 150 new recurring Quranic words",
        pThree: "Completion of 60 – 75% Quranic Grammar",
        pFour: "Obtaining secondary level of Fundamental Quranic Grammar",
        pFive: "Once completed, the application of those grammatical rules will be studied through reading 3 Sura(s) ; which will prepare a student to enroll Advanced Quran Learning Programme at any stage ",
        pSix: "",
        pSeven: "",
        pEight: "",
        pNine: "",
        pTen: "",
    },
    {
        title: "Advanced Quran Learning Programme",
        cOutLine: "Learning Outcomes:",
        pOne: "Completely focused on deep learning of Quran",
        pTwo: "Quranic Word meaning ",
        pThree: "Whole Ayat meaning",
        pFour: "Grammatical analysis of words",
        pFive: "Tafseer",
        pSix: "Basic teachings of an Ayat",
        pSeven: "Etc",
        pEight: "The application of the grammatical rules will be studied through reading several Sura(s) such as Sura Baqara, Sura Al-e-Imran, Sura Nisa etc",
        pNine: "",
        pTen: "",
    },
];

export default CourseData;